if(NOT DEFINED PLEXDB_ENABLE_TESTS)
    option(PLEXDB_ENABLE_TESTS "Build unit tests" OFF)
endif()
if(NOT DEFINED PLEXDB_DISABLE_EXCEPTIONS)
    option(PLEXDB_DISABLE_EXCEPTIONS "Disable exceptions globally" ON)
endif()
if(NOT DEFINED PLEXDB_DEBUG)
    option(PLEXDB_DEBUG "Build debug checks" ON)
endif()
if(NOT DEFINED PLEXDB_ENABLE_LOGGING)
    option(PLEXDB_ENABLE_LOGGING "Enable structured logging hooks" OFF)
endif()
