if(NOT DEFINED PLEXDB_ENABLE_TESTS)
  option(PLEXDB_ENABLE_TESTS "Build unit tests" OFF)
endif()
if(NOT DEFINED PLEXDB_DISABLE_EXCEPTIONS)
  option(PLEXDB_DISABLE_EXCEPTIONS "Disable exceptions globally" ON)
endif()
if(NOT DEFINED PLEXDB_DEBUG)
  option(PLEXDB_DEBUG "Build debug checks" OFF)
endif()
if(NOT DEFINED PLEXDB_ENABLE_PLUGINS)
  option(PLEXDB_ENABLE_PLUGINS "Enable structured logging hooks" OFF)
endif()
if(NOT DEFINED PLEXDB_ENABLE_TRACY_PROFILER)
  option(PLEXDB_ENABLE_TRACY_PROFILER "Enable collection of tracy profiling data (only enable if you know what this means)" OFF)
endif()
# @todo detect debugger
# @todo investigate how gdb interferes with these
if(NOT DEFINED PLEXDB_ENABLE_USER_KILL_SIGNAL)
  option(PLEXDB_ENABLE_USER_KILL_SIGNAL "Enable treating SIGUSR1 as a kill signal and ignoring SIGNINT and SIGTERM (can help when attaching debuggers)" OFF)
endif()
if(NOT DEFINED PLEXDB_FTIME_TRACE)
  option(PLEXDB_FTIME_TRACE "Emit per-TU compile-time traces (view in chrome://tracing or speedscope)" OFF)
endif()
